# pandas- Groupby function

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('movies_data.csv')
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [3]:
df['genre'].nunique()

16

In [4]:
df['genre'].value_counts()

Drama        278
Comedy       156
Action       136
Crime        124
Biography     77
Adventure     75
Animation     62
Horror        29
Mystery       16
Western        9
Thriller       5
Sci-Fi         5
Film-Noir      3
Family         2
History        1
Fantasy        1
Name: genre, dtype: int64

In [5]:
df.groupby('genre').groups.keys()

dict_keys(['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 'History', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller', 'Western'])

In [6]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [7]:
df.groupby('genre').first()

,star_rating,title,content_rating,duration,actors_list
genre,,,,,
Action,9.0,The Dark Knight,PG-13,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
Adventure,8.9,The Lord of the Rings: The Return of the King,PG-13,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
Animation,8.6,Spirited Away,PG,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
Biography,8.9,Schindler's List,R,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
Comedy,8.6,Life Is Beautiful,PG-13,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
Crime,9.3,The Shawshank Redemption,R,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
Drama,8.9,12 Angry Men,NOT RATED,96,"[u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals..."
Family,7.9,E.T. the Extra-Terrestrial,PG,115,"[u'Henry Thomas', u'Drew Barrymore', u'Peter C..."
Fantasy,7.7,The City of Lost Children,R,112,"[u'Ron Perlman', u'Daniel Emilfork', u'Judith ..."
Film-Noir,8.3,The Third Man,NOT RATED,93,"[u'Orson Welles', u'Joseph Cotten', u'Alida Va..."
History,8.0,Battleship Potemkin,UNRATED,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
Horror,8.6,Psycho,R,109,"[u'Anthony Perkins', u'Janet Leigh', u'Vera Mi..."
Mystery,8.6,Rear Window,APPROVED,112,"[u'James Stewart', u'Grace Kelly', u'Wendell C..."
Sci-Fi,8.2,Blade Runner,R,117,"[u'Harrison Ford', u'Rutger Hauer', u'Sean You..."
Thriller,8.0,Shadow of a Doubt,APPROVED,108,"[u'Teresa Wright', u'Joseph Cotten', u'Macdona..."
Western,8.9,"The Good, the Bad and the Ugly",NOT RATED,161,"[u'Clint Eastwood', u'Eli Wallach', u'Lee Van ..."

In [ ]:
['Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 
 'Crime', 'Drama', 'Family', 'Fantasy', 'Film-Noir', 
 'History', 'Horror', 'Mystery', 'Sci-Fi', 'Thriller', 'Western']

In [8]:
df.groupby('genre').get_group('History')

,star_rating,title,content_rating,genre,duration,actors_list
338,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."

In [10]:
df.groupby('genre').get_group('Family')

,star_rating,title,content_rating,genre,duration,actors_list
468,7.9,E.T. the Extra-Terrestrial,PG,Family,115,"[u'Henry Thomas', u'Drew Barrymore', u'Peter C..."
497,7.8,Willy Wonka & the Chocolate Factory,G,Family,100,"[u'Gene Wilder', u'Jack Albertson', u'Peter Os..."

In [12]:
df.groupby('genre').get_group('Action').reset_index(drop=True).to_csv('Action_Movies.csv')

In [13]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [14]:
df.groupby('content_rating').get_group('PG-13')

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
...,...,...,...,...,...,...
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
965,7.4,Limitless,PG-13,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
966,7.4,The Simpsons Movie,PG-13,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [15]:
df['content_rating'].value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
NC-17          7
PASSED         7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

In [17]:
df.groupby('content_rating').get_group('APPROVED').shape

(47, 6)

In [18]:
df.groupby('content_rating').get_group('GP')

,star_rating,title,content_rating,genre,duration,actors_list
282,8.1,Harold and Maude,GP,Comedy,91,"[u'Ruth Gordon', u'Bud Cort', u'Vivian Pickles']"
302,8.0,Patton,GP,Biography,172,"[u'George C. Scott', u'Karl Malden', u'Stephen..."
691,7.7,Kelly's Heroes,GP,Action,144,"[u'Clint Eastwood', u'Telly Savalas', u'Don Ri..."

In [19]:
df.groupby(['content_rating','genre']).get_group(('PASSED','Comedy'))

,star_rating,title,content_rating,genre,duration,actors_list
29,8.6,City Lights,PASSED,Comedy,87,"[u'Charles Chaplin', u'Virginia Cherrill', u'F..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
358,8.0,The Lady Vanishes,PASSED,Comedy,96,"[u'Margaret Lockwood', u'Michael Redgrave', u'..."

In [22]:
df.groupby(['content_rating','genre']).get_group(('PG-13','Comedy'))

,star_rating,title,content_rating,genre,duration,actors_list
25,8.6,Life Is Beautiful,PG-13,Comedy,116,"[u'Roberto Benigni', u'Nicoletta Braschi', u'G..."
60,8.5,3 Idiots,PG-13,Comedy,170,"[u'Aamir Khan', u'Madhavan', u'Mona Singh']"
314,8.0,Crimes and Misdemeanors,PG-13,Comedy,104,"[u'Martin Landau', u'Woody Allen', u'Bill Bern..."
356,8.0,The Artist,PG-13,Comedy,100,"[u'Jean Dujardin', u'B\xe9r\xe9nice Bejo', u'J..."
370,8.0,Hannah and Her Sisters,PG-13,Comedy,103,"[u'Mia Farrow', u'Dianne Wiest', u'Michael Cai..."
459,7.9,Ferris Bueller's Day Off,PG-13,Comedy,103,"[u'Matthew Broderick', u'Alan Ruck', u'Mia Sara']"
542,7.8,(500) Days of Summer,PG-13,Comedy,95,"[u'Zooey Deschanel', u'Joseph Gordon-Levitt', ..."
578,7.8,As Good as It Gets,PG-13,Comedy,139,"[u'Jack Nicholson', u'Helen Hunt', u'Greg Kinn..."
622,7.7,The Dinner Game,PG-13,Comedy,80,"[u'Thierry Lhermitte', u'Jacques Villeret', u'..."
639,7.7,Billy Elliot,PG-13,Comedy,110,"[u'Jamie Bell', u'Julie Walters', u'Jean Heywo..."
667,7.7,Midnight in Paris,PG-13,Comedy,94,"[u'Owen Wilson', u'Rachel McAdams', u'Kathy Ba..."
696,7.7,Stranger Than Fiction,PG-13,Comedy,113,"[u'Will Ferrell', u'Emma Thompson', u'Dustin H..."
735,7.6,The Naked Gun: From the Files of Police Squad!,PG-13,Comedy,85,"[u'Leslie Nielsen', u'Priscilla Presley', u'O...."
806,7.6,Juno,PG-13,Comedy,96,"[u'Ellen Page', u'Michael Cera', u'Jennifer Ga..."
821,7.6,Christmas Vacation,PG-13,Comedy,97,"[u'Chevy Chase', u""Beverly D'Angelo"", u'Juliet..."
857,7.5,Pleasantville,PG-13,Comedy,124,"[u'Tobey Maguire', u'Jeff Daniels', u'Joan All..."
867,7.5,Best in Show,PG-13,Comedy,90,"[u'Fred Willard', u'Eugene Levy', u""Catherine ..."
868,7.5,Everything Is Illuminated,PG-13,Comedy,106,"[u'Elijah Wood', u'Eugene Hutz', u'Boris Leskin']"
929,7.5,Say Anything...,PG-13,Comedy,100,"[u'John Cusack', u'Ione Skye', u'John Mahoney']"
934,7.4,"Crazy, Stupid, Love.",PG-13,Comedy,118,"[u'Steve Carell', u'Ryan Gosling', u'Julianne ..."
940,7.4,Much Ado About Nothing,PG-13,Comedy,111,"[u'Kenneth Branagh', u'Emma Thompson', u'Keanu..."
942,7.4,Raising Arizona,PG-13,Comedy,94,"[u'Nicolas Cage', u'Holly Hunter', u'Trey Wils..."
960,7.4,The Way Way Back,PG-13,Comedy,103,"[u'Steve Carell', u'Toni Collette', u'Allison ..."

In [23]:
df.groupby('genre')['star_rating'].mean()

genre
Action       7.884559
Adventure    7.933333
Animation    7.914516
Biography    7.862338
Comedy       7.822436
Crime        7.916935
Drama        7.902518
Family       7.850000
Fantasy      7.700000
Film-Noir    8.033333
History      8.000000
Horror       7.806897
Mystery      7.975000
Sci-Fi       7.920000
Thriller     7.680000
Western      8.255556
Name: star_rating, dtype: float64

In [24]:
df.groupby('genre')['star_rating'].max()

genre
Action       9.0
Adventure    8.9
Animation    8.6
Biography    8.9
Comedy       8.6
Crime        9.3
Drama        8.9
Family       7.9
Fantasy      7.7
Film-Noir    8.3
History      8.0
Horror       8.6
Mystery      8.6
Sci-Fi       8.2
Thriller     8.0
Western      8.9
Name: star_rating, dtype: float64

In [25]:
df.groupby('genre')['star_rating'].min()

genre
Action       7.4
Adventure    7.4
Animation    7.4
Biography    7.4
Comedy       7.4
Crime        7.4
Drama        7.4
Family       7.8
Fantasy      7.7
Film-Noir    7.7
History      8.0
Horror       7.4
Mystery      7.4
Sci-Fi       7.7
Thriller     7.5
Western      7.6
Name: star_rating, dtype: float64

In [26]:
df.groupby('genre')['duration'].max()

genre
Action       205
Adventure    224
Animation    134
Biography    202
Comedy       187
Crime        229
Drama        242
Family       115
Fantasy      112
Film-Noir    111
History       66
Horror       146
Mystery      160
Sci-Fi       132
Thriller     120
Western      175
Name: duration, dtype: int64

In [27]:
df.groupby('genre')['duration'].min()

genre
Action        80
Adventure     89
Animation     75
Biography     85
Comedy        68
Crime         67
Drama         64
Family       100
Fantasy      112
Film-Noir     88
History       66
Horror        70
Mystery       69
Sci-Fi        91
Thriller     107
Western       85
Name: duration, dtype: int64

In [29]:
df.groupby('genre').mean()

           star_rating    duration
genre
Action        7.884559  126.485294
Adventure     7.933333  134.840000
Animation     7.914516   96.596774
Biography     7.862338  131.844156
Comedy        7.822436  107.602564
Crime         7.916935  122.298387
Drama         7.902518  126.539568
Family        7.850000  107.500000
Fantasy       7.700000  112.000000
Film-Noir     8.033333   97.333333
History       8.000000   66.000000
Horror        7.806897  102.517241
Mystery       7.975000  115.625000
Sci-Fi        7.920000  109.000000
Thriller      7.680000  114.200000
Western       8.255556  136.666667

# loc

In [30]:
df

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [31]:
df['content_rating'].value_counts()

R            460
PG-13        189
PG           123
NOT RATED     65
APPROVED      47
UNRATED       38
G             32
NC-17          7
PASSED         7
X              4
GP             3
TV-MA          1
Name: content_rating, dtype: int64

In [32]:
df.loc[df['content_rating']=='R']

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
...,...,...,...,...,...,...
968,7.4,The English Patient,R,Drama,162,"[u'Ralph Fiennes', u'Juliette Binoche', u'Will..."
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
971,7.4,Death at a Funeral,R,Comedy,90,"[u'Matthew Macfadyen', u'Peter Dinklage', u'Ew..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [33]:
df.loc[df['content_rating']=='PG']

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
30,8.6,Spirited Away,PG,Animation,125,"[u'Daveigh Chase', u'Suzanne Pleshette', u'Miy..."
32,8.6,Casablanca,PG,Drama,102,"[u'Humphrey Bogart', u'Ingrid Bergman', u'Paul..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
...,...,...,...,...,...,...
956,7.4,Manhattan Murder Mystery,PG,Comedy,104,"[u'Woody Allen', u'Diane Keaton', u'Jerry Adler']"
962,7.4,Driving Miss Daisy,PG,Comedy,99,"[u'Morgan Freeman', u'Jessica Tandy', u'Dan Ay..."
974,7.4,Tootsie,PG,Comedy,116,"[u'Dustin Hoffman', u'Jessica Lange', u'Teri G..."
975,7.4,Back to the Future Part III,PG,Adventure,118,"[u'Michael J. Fox', u'Christopher Lloyd', u'Ma..."
977,7.4,Poltergeist,PG,Horror,114,"[u'JoBeth Williams', u""Heather O'Rourke"", u'Cr..."

In [35]:
x= (df['content_rating']=='PG')&(df['genre']=='Action')
x.iloc[:15]

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
dtype: bool

In [36]:
df.loc[(df['content_rating']=='PG')&(df['genre']=='Action')]

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
80,8.4,Star Wars: Episode VI - Return of the Jedi,PG,Action,134,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
327,8.0,The Adventures of Robin Hood,PG,Action,102,"[u'Errol Flynn', u'Olivia de Havilland', u'Bas..."
420,7.9,The Man Who Would Be King,PG,Action,129,"[u'Sean Connery', u'Michael Caine', u'Christop..."
586,7.7,Star Trek II: The Wrath of Khan,PG,Action,113,"[u'William Shatner', u'Leonard Nimoy', u'DeFor..."
748,7.6,The Hunt for Red October,PG,Action,135,"[u'Sean Connery', u'Alec Baldwin', u'Scott Gle..."
753,7.6,Escape from Alcatraz,PG,Action,112,"[u'Clint Eastwood', u'Patrick McGoohan', u'Rob..."
764,7.6,Indiana Jones and the Temple of Doom,PG,Action,118,"[u'Harrison Ford', u'Kate Capshaw', u'Jonathan..."
908,7.5,Bullitt,PG,Action,114,"[u'Steve McQueen', u'Jacqueline Bisset', u'Rob..."

In [38]:
df.loc[(df['content_rating']=='PG')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))]

,star_rating,title,content_rating,genre,duration,actors_list
12,8.8,Star Wars: Episode V - The Empire Strikes Back,PG,Action,124,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
19,8.7,Star Wars,PG,Action,121,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
37,8.6,Raiders of the Lost Ark,PG,Action,115,"[u'Harrison Ford', u'Karen Allen', u'Paul Free..."
80,8.4,Star Wars: Episode VI - Return of the Jedi,PG,Action,134,"[u'Mark Hamill', u'Harrison Ford', u'Carrie Fi..."
154,8.2,Cool Hand Luke,PG,Crime,126,"[u'Paul Newman', u'George Kennedy', u'Strother..."
171,8.2,Dial M for Murder,PG,Crime,105,"[u'Ray Milland', u'Grace Kelly', u'Robert Cumm..."
200,8.1,Le Samourai,PG,Crime,101,"[u'Alain Delon', u'Nathalie Delon', u'Fran\xe7..."
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
327,8.0,The Adventures of Robin Hood,PG,Action,102,"[u'Errol Flynn', u'Olivia de Havilland', u'Bas..."
420,7.9,The Man Who Would Be King,PG,Action,129,"[u'Sean Connery', u'Michael Caine', u'Christop..."
425,7.9,Badlands,PG,Crime,94,"[u'Martin Sheen', u'Sissy Spacek', u'Warren Oa..."
495,7.8,The Day of the Jackal,PG,Crime,143,"[u'Edward Fox', u'Terence Alexander', u'Michel..."
586,7.7,Star Trek II: The Wrath of Khan,PG,Action,113,"[u'William Shatner', u'Leonard Nimoy', u'DeFor..."
748,7.6,The Hunt for Red October,PG,Action,135,"[u'Sean Connery', u'Alec Baldwin', u'Scott Gle..."
753,7.6,Escape from Alcatraz,PG,Action,112,"[u'Clint Eastwood', u'Patrick McGoohan', u'Rob..."
764,7.6,Indiana Jones and the Temple of Doom,PG,Action,118,"[u'Harrison Ford', u'Kate Capshaw', u'Jonathan..."
908,7.5,Bullitt,PG,Action,114,"[u'Steve McQueen', u'Jacqueline Bisset', u'Rob..."

In [39]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
...,...,...,...,...,...,...
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [40]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']<=180)]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
950,7.4,Bound,R,Crime,108,"[u'Jennifer Tilly', u'Gina Gershon', u'Joe Pan..."
963,7.4,La Femme Nikita,R,Action,118,"[u'Anne Parillaud', u'Marc Duret', u'Patrick F..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
969,7.4,Law Abiding Citizen,R,Crime,109,"[u'Gerard Butler', u'Jamie Foxx', u'Leslie Bibb']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [41]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']>=180)]

,star_rating,title,content_rating,genre,duration,actors_list
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."

In [42]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']<=180)
      & (df['duration']>=120)]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
20,8.7,The Matrix,R,Action,136,"[u'Keanu Reeves', u'Laurence Fishburne', u'Car..."
21,8.7,City of God,R,Crime,130,"[u'Alexandre Rodrigues', u'Matheus Nachtergael..."
...,...,...,...,...,...,...
884,7.5,Open Range,R,Action,139,"[u'Kevin Costner', u'Robert Duvall', u'Diego L..."
893,7.5,In the Bedroom,R,Crime,130,"[u'Tom Wilkinson', u'Sissy Spacek', u'Nick Sta..."
918,7.5,Running Scared,R,Action,122,"[u'Paul Walker', u'Cameron Bright', u'Chazz Pa..."
967,7.4,The Rock,R,Action,136,"[u'Sean Connery', u'Nicolas Cage', u'Ed Harris']"
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [43]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']<=180)
      & (df['duration']>=150)]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
36,8.6,Saving Private Ryan,R,Action,169,"[u'Tom Hanks', u'Matt Damon', u'Tom Sizemore']"
44,8.5,Gladiator,R,Action,155,"[u'Russell Crowe', u'Joaquin Phoenix', u'Conni..."
49,8.5,The Departed,R,Crime,151,"[u'Leonardo DiCaprio', u'Matt Damon', u'Jack N..."
82,8.4,Braveheart,R,Action,177,"[u'Mel Gibson', u'Sophie Marceau', u'Patrick M..."
115,8.3,Scarface,R,Crime,170,"[u'Al Pacino', u'Michelle Pfeiffer', u'Steven ..."
129,8.3,Ran,R,Action,162,"[u'Tatsuya Nakadai', u'Akira Terao', u'Jinpach..."
135,8.3,Heat,R,Action,170,"[u'Al Pacino', u'Robert De Niro', u'Val Kilmer']"
268,8.1,The Raid 2,R,Action,150,"[u'Iko Uwais', u'Yayan Ruhian', u'Arifin Putra']"
290,8.1,Prisoners,R,Crime,153,"[u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ..."
300,8.0,Dogville,R,Crime,178,"[u'Nicole Kidman', u'Paul Bettany', u'Lauren B..."
426,7.9,A Prophet,R,Crime,155,"[u'Tahar Rahim', u'Niels Arestrup', u'Adel Ben..."
466,7.9,The Girl with the Dragon Tattoo,R,Crime,158,"[u'Daniel Craig', u'Rooney Mara', u'Christophe..."
482,7.8,The Girl with the Dragon Tattoo,R,Crime,152,"[u'Michael Nyqvist', u'Noomi Rapace', u'Ewa Fr..."
613,7.7,The Last Samurai,R,Action,154,"[u'Tom Cruise', u'Ken Watanabe', u'Billy Conno..."
677,7.7,Zodiac,R,Crime,157,"[u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M..."
707,7.6,Watchmen,R,Action,162,"[u'Jackie Earle Haley', u'Patrick Wilson', u'C..."
711,7.6,The Godfather: Part III,R,Crime,162,"[u'Al Pacino', u'Diane Keaton', u'Andy Garcia']"
828,7.5,Gangs of New York,R,Crime,167,"[u'Leonardo DiCaprio', u'Cameron Diaz', u'Dani..."
836,7.5,Jackie Brown,R,Crime,154,"[u'Pam Grier', u'Samuel L. Jackson', u'Robert ..."

In [44]:
df.loc[(df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']<=180)
      & (df['duration']>=150)
      & (df['star_rating']>=8)]

,star_rating,title,content_rating,genre,duration,actors_list
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
36,8.6,Saving Private Ryan,R,Action,169,"[u'Tom Hanks', u'Matt Damon', u'Tom Sizemore']"
44,8.5,Gladiator,R,Action,155,"[u'Russell Crowe', u'Joaquin Phoenix', u'Conni..."
49,8.5,The Departed,R,Crime,151,"[u'Leonardo DiCaprio', u'Matt Damon', u'Jack N..."
82,8.4,Braveheart,R,Action,177,"[u'Mel Gibson', u'Sophie Marceau', u'Patrick M..."
115,8.3,Scarface,R,Crime,170,"[u'Al Pacino', u'Michelle Pfeiffer', u'Steven ..."
129,8.3,Ran,R,Action,162,"[u'Tatsuya Nakadai', u'Akira Terao', u'Jinpach..."
135,8.3,Heat,R,Action,170,"[u'Al Pacino', u'Robert De Niro', u'Val Kilmer']"
268,8.1,The Raid 2,R,Action,150,"[u'Iko Uwais', u'Yayan Ruhian', u'Arifin Putra']"
290,8.1,Prisoners,R,Crime,153,"[u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ..."
300,8.0,Dogville,R,Crime,178,"[u'Nicole Kidman', u'Paul Bettany', u'Lauren B..."

In [45]:
condition= ((df['content_rating']=='R')
       &((df['genre']=='Action')
      |(df['genre']=='Crime'))
      & (df['duration']<=180)
      & (df['duration']>=150)
      & (df['star_rating']>=8))
df.loc[condition,['title','actors_list']]

                   title                                        actors_list
1          The Godfather    [u'Marlon Brando', u'Al Pacino', u'James Caan']
4           Pulp Fiction  [u'John Travolta', u'Uma Thurman', u'Samuel L....
36   Saving Private Ryan     [u'Tom Hanks', u'Matt Damon', u'Tom Sizemore']
44             Gladiator  [u'Russell Crowe', u'Joaquin Phoenix', u'Conni...
49          The Departed  [u'Leonardo DiCaprio', u'Matt Damon', u'Jack N...
82            Braveheart  [u'Mel Gibson', u'Sophie Marceau', u'Patrick M...
115             Scarface  [u'Al Pacino', u'Michelle Pfeiffer', u'Steven ...
129                  Ran  [u'Tatsuya Nakadai', u'Akira Terao', u'Jinpach...
135                 Heat   [u'Al Pacino', u'Robert De Niro', u'Val Kilmer']
268           The Raid 2   [u'Iko Uwais', u'Yayan Ruhian', u'Arifin Putra']
290            Prisoners  [u'Hugh Jackman', u'Jake Gyllenhaal', u'Viola ...
300             Dogville  [u'Nicole Kidman', u'Paul Bettany', u'Lauren B...

In [46]:
df['genre'].unique()

array(['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror', 'Film-Noir', 'Sci-Fi',
       'History', 'Thriller', 'Family', 'Fantasy'], dtype=object)

In [48]:
df.loc[(df['genre']=='Crime')
      |(df['genre']=='Action')
      |(df['genre']=='Drama')]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [49]:
df.loc[df['genre'].isin(['Drama','Action','Crime'])]

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."
...,...,...,...,...,...,...
970,7.4,Wonder Boys,R,Drama,107,"[u'Michael Douglas', u'Tobey Maguire', u'Franc..."
972,7.4,Blue Valentine,NC-17,Drama,112,"[u'Ryan Gosling', u'Michelle Williams', u'John..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."
978,7.4,Wall Street,R,Crime,126,"[u'Charlie Sheen', u'Michael Douglas', u'Tamar..."

In [50]:
geners_list=['Crime', 'Action', 'Drama', 'Western', 'Adventure', 'Biography',
       'Comedy', 'Animation', 'Mystery', 'Horror']

In [52]:
df.loc[(df['genre'].isin(geners_list))& (df['content_rating']=='PG-13')]

,star_rating,title,content_rating,genre,duration,actors_list
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
10,8.8,The Lord of the Rings: The Fellowship of the Ring,PG-13,Adventure,178,"[u'Elijah Wood', u'Ian McKellen', u'Orlando Bl..."
11,8.8,Inception,PG-13,Action,148,"[u'Leonardo DiCaprio', u'Joseph Gordon-Levitt'..."
13,8.8,Forrest Gump,PG-13,Drama,142,"[u'Tom Hanks', u'Robin Wright', u'Gary Sinise']"
...,...,...,...,...,...,...
964,7.4,Lincoln,PG-13,Biography,150,"[u'Daniel Day-Lewis', u'Sally Field', u'David ..."
965,7.4,Limitless,PG-13,Mystery,105,"[u'Bradley Cooper', u'Anna Friel', u'Abbie Cor..."
966,7.4,The Simpsons Movie,PG-13,Animation,87,"[u'Dan Castellaneta', u'Julie Kavner', u'Nancy..."
973,7.4,The Cider House Rules,PG-13,Drama,126,"[u'Tobey Maguire', u'Charlize Theron', u'Micha..."
976,7.4,Master and Commander: The Far Side of the World,PG-13,Action,138,"[u'Russell Crowe', u'Paul Bettany', u'Billy Bo..."

In [58]:
df.loc[(df['genre'].isin(geners_list))& (df['star_rating']==8)]

,star_rating,title,content_rating,genre,duration,actors_list
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
298,8.0,The Graduate,APPROVED,Comedy,106,"[u'Dustin Hoffman', u'Anne Bancroft', u'Kathar..."
299,8.0,Jurassic Park,PG-13,Adventure,127,"[u'Sam Neill', u'Laura Dern', u'Jeff Goldblum']"
300,8.0,Dogville,R,Crime,178,"[u'Nicole Kidman', u'Paul Bettany', u'Lauren B..."
301,8.0,Furious 7,PG-13,Action,137,"[u'Vin Diesel', u'Paul Walker', u'Dwayne Johns..."
...,...,...,...,...,...,...
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
390,8.0,Letters from Iwo Jima,R,Drama,141,"[u'Ken Watanabe', u'Kazunari Ninomiya', u'Tsuy..."
391,8.0,Edge of Tomorrow,PG-13,Action,113,"[u'Tom Cruise', u'Emily Blunt', u'Bill Paxton']"
392,8.0,Glory,R,Drama,122,"[u'Matthew Broderick', u'Denzel Washington', u..."
393,8.0,The African Queen,PG,Adventure,105,"[u'Humphrey Bogart', u'Katharine Hepburn', u'R..."